=== toxin98/photography-analog-json-schemas/example.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Metadata Schema",
  "type": "array",

  "items": {
    "type": "object",
    "required": ["id", "film", "camera", "note", "date", "development"],

    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[0-9]{4}$",
        "description": "Roll unique ID (e.g., 0001)"
      },

      "film": { "$ref": "./film.schema.json" },

      "camera": {
        "type": "string",
        "description": "Camera model",
        "enum": [
          "Nikon F2",
          "Pentax KX"
        ]
      },

      "note": {
        "type": "string"
      },

      "date": {
        "type": "object",
        "required": ["started", "finished"],
        "properties": {
          "started": { "type": "string", "format": "date" },
          "finished": { "type": "string", "format": "date" }
        },
        "additionalProperties": false
      },

      "development": {
        "type": "object",
        "required": ["lab", "process", "scanning"],
        "properties": {
          "lab": { "$ref": "./lab.schema.json" },
          "process": { "$ref": "./process.schema.json" },
          "scanning": { "$ref": "./scanning.schema.json" }
        },
        "additionalProperties": false
      }
    },

    "additionalProperties": false
  }
}

=== toxin98/photography-analog-json-schemas/example.json
[{
  "id": "0001",
  "film": "Kodak 5219",
  "camera": "Nikon F2",
  "date": {
    "started": "2021-09-28",
    "finished": "2022-02-16"
  },
  "development": {
    "lab": "金陵银盐馆",
    "process": "ECN-2",
    "scanning": {
      "method": "scanner",
      "brand": "Noritsu",
      "model": "HS-1800"
    }
  },
  "note": "Pushed to 1600"
},
{
  "id": "0002",
  "film": "Fujifilm C200",
  "camera": "Pentax KX",
  "date": {
    "started": "2022-03-09",
    "finished": "2022-05-11"
  },
  "development": {
    "lab": "画英雄",
    "process": "C-41",
    "scanning": {
      "method": "camera",
      "details": "5d4 + 24-70"
    }
  },
  "note": "2014年过期胶卷"
}]
